command_type: position  # position | velocity
active_profile: chirp  # step | sine | chirp | ramp | ramp_b | ramp_step | nstep
file_label: null

step:
  initial_wait: 1.0
  step_duration: 5.0
  output_amplitude: 0.8
  offset: 0.0
  repeat: false

sine:
  initial_wait: 1.0
  output_amplitude: 0.5
  frequency_hz: 1.5
  offset: 0.0

chirp:
  initial_wait: 1.0
  output_amplitude: 0.2      # [turn] 振幅を少し大きく
  start_frequency_hz: 0.2
  end_frequency_hz: 2.5      # 高周波まで回す
  duration: 10.0
  post_duration: 0.0          # [s] chirp終了後にログを伸ばす時間
  offset: 0.0
  window: smootherstep
  window_ramp_duration: 1.0  # [s] 窓関数の立ち上げ時間

pulse:
  initial_wait: 1.0
  start_value: 0.0
  end_value: 0.01
  ramp_duration: 0.02
  hold_duration: 0.03
  return_duration: 0.02
  repeat: false

ramp:
  initial_wait: 1.0
  start_value: 0.0
  end_value: 0.5
  ramp_duration: 5.0
  hold_duration: 2.0
  return_duration: 5.0
  repeat: false

ramp_b:
  initial_wait: 1.0
  start_value: 0.0
  end_value: 0.5
  ramp_duration: 2.0
  hold_duration: 0.0
  return_duration: 1.0
  start_hold_duration: 0.0
  repeat: true

ramp_step:
  initial_wait: 1.0
  start_value: 0.0
  end_value: 0.5
  ramp_duration: 5.0
  hold_duration: 0.3
  return_duration: 0.0
  repeat: false
  step:
    amplitude: -0.5
    duration: 20.0
    start_after: -0.01
    repeat: false
    period: 0.0
    offset_in_cycle: 0.0
    align_to_ramp_end: true

nstep:
  initial_wait: 1.0
  values: [0.2, 0, 0.2, 0.0]
  hold_duration: 4.0
  repeat: true
  wait_value: 0.0
